"""initial schema

Revision ID: af3b76bc449a
Revises: 
Create Date: 2026-07-19 17:04:25.731677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af3b76bc449a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_plans',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('coverage_lovelace', sa.BigInteger(), nullable=False),
    sa.Column('premium_lovelace', sa.BigInteger(), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('max_claims_per_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_insurance_plans_name'))
    )
    op.create_table('pool_snapshots',
    sa.Column('total_pool_lovelace', sa.BigInteger(), nullable=False),
    sa.Column('allocated_lovelace', sa.BigInteger(), nullable=False),
    sa.Column('liquid_lovelace', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pool_snapshots'))
    )
    op.create_index(op.f('ix_pool_snapshots_snapshot_at'), 'pool_snapshots', ['snapshot_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('policies',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'LAPSED', 'CANCELLED', name='policystatus', native_enum=False, length=20), nullable=False),
    sa.Column('commitment_hash', sa.String(length=130), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_premium_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], name=op.f('fk_policies_plan_id_insurance_plans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_policies_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('commitment_hash', name=op.f('uq_policies_commitment_hash'))
    )
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    op.create_index(op.f('ix_policies_user_id'), 'policies', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('PREMIUM', 'PAYOUT', 'ALLOCATION', 'DEALLOCATION', 'YIELD', name='transactiontype', native_enum=False, length=20), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='transactiondirection', native_enum=False, length=5), nullable=False),
    sa.Column('amount_lovelace', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_tx_hash'), 'transactions', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets'))
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=True)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('yield_allocations',
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('amount_lovelace', sa.BigInteger(), nullable=False),
    sa.Column('target_bps', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'WITHDRAWN', name='allocationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('allocated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['allocated_by'], ['users.id'], name=op.f('fk_yield_allocations_allocated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yield_allocations'))
    )
    op.create_table('claims',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('claim_reference', sa.String(length=30), nullable=False),
    sa.Column('amount_lovelace', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'PROOF_VERIFIED', 'APPROVED', 'PAID', 'REJECTED', name='claimstatus', native_enum=False, length=20), nullable=False),
    sa.Column('payout_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_claims_policy_id_policies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('payout_tx_hash', name=op.f('uq_claims_payout_tx_hash'))
    )
    op.create_index(op.f('ix_claims_claim_reference'), 'claims', ['claim_reference'], unique=True)
    op.create_index(op.f('ix_claims_policy_id'), 'claims', ['policy_id'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('premium_payments',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('amount_lovelace', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_premium_payments_policy_id_policies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_premium_payments'))
    )
    op.create_index(op.f('ix_premium_payments_policy_id'), 'premium_payments', ['policy_id'], unique=False)
    op.create_index(op.f('ix_premium_payments_tx_hash'), 'premium_payments', ['tx_hash'], unique=True)
    op.create_table('zk_proof_records',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('proof_hash', sa.String(length=130), nullable=False),
    sa.Column('verifier', sa.String(length=40), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_zk_proof_records_claim_id_claims')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zk_proof_records')),
    sa.UniqueConstraint('claim_id', name=op.f('uq_zk_proof_records_claim_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zk_proof_records')
    op.drop_index(op.f('ix_premium_payments_tx_hash'), table_name='premium_payments')
    op.drop_index(op.f('ix_premium_payments_policy_id'), table_name='premium_payments')
    op.drop_table('premium_payments')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_policy_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_reference'), table_name='claims')
    op.drop_table('claims')
    op.drop_table('yield_allocations')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_tx_hash'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_policies_user_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_status'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pool_snapshots_snapshot_at'), table_name='pool_snapshots')
    op.drop_table('pool_snapshots')
    op.drop_table('insurance_plans')
    # ### end Alembic commands ###
