"""wallet challenges

Revision ID: c8de94c8744d
Revises: cf2c1a89da39
Create Date: 2026-07-19 18:30:29.148407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c8de94c8744d'
down_revision: Union[str, None] = 'cf2c1a89da39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_challenges',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('nonce', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallet_challenges_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_challenges')),
    sa.UniqueConstraint('nonce', name=op.f('uq_wallet_challenges_nonce'))
    )
    op.create_index(op.f('ix_wallet_challenges_address'), 'wallet_challenges', ['address'], unique=False)
    op.create_index(op.f('ix_wallet_challenges_user_id'), 'wallet_challenges', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_challenges_user_id'), table_name='wallet_challenges')
    op.drop_index(op.f('ix_wallet_challenges_address'), table_name='wallet_challenges')
    op.drop_table('wallet_challenges')
    # ### end Alembic commands ###
