"""widen tx hash columns

Revision ID: f198127e1111
Revises: c8de94c8744d
Create Date: 2026-07-20 23:32:08.784769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f198127e1111'
down_revision: Union[str, None] = 'c8de94c8744d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'payout_tx_hash',
               existing_type=sa.VARCHAR(length=66),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('premium_payments', 'tx_hash',
               existing_type=sa.VARCHAR(length=66),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('transactions', 'tx_hash',
               existing_type=sa.VARCHAR(length=66),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('yield_allocations', 'tx_hash',
               existing_type=sa.VARCHAR(length=66),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yield_allocations', 'tx_hash',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=66),
               existing_nullable=True)
    op.alter_column('transactions', 'tx_hash',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=66),
               existing_nullable=True)
    op.alter_column('premium_payments', 'tx_hash',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=66),
               existing_nullable=False)
    op.alter_column('claims', 'payout_tx_hash',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=66),
               existing_nullable=True)
    # ### end Alembic commands ###
