import type { Blueprint, ValidatorBlueprint } from "@forge/domain";
import {
  camelCase,
  generateNamedTypeDeclarations,
  pascalCase,
  typeExpressionFor,
} from "./type-mapper.js";

function identifierForValidator(title: string): string {
  const parts = title.split(".");
  const relevant = parts.length >= 2 ? parts.slice(-2) : parts;
  return pascalCase(relevant.join("_"));
}

function generateValidatorSection(blueprint: Blueprint, validator: ValidatorBlueprint): string {
  const identifier = identifierForValidator(validator.title);
  const datumType = validator.datum
    ? typeExpressionFor(blueprint, validator.datum.schema)
    : "undefined";
  const redeemerType = typeExpressionFor(blueprint, validator.redeemer.schema);

  return [
    `export type ${identifier}Datum = ${datumType};`,
    `export type ${identifier}Redeemer = ${redeemerType};`,
    `export const ${camelCase(identifier)}Validator = {`,
    `  title: ${JSON.stringify(validator.title)},`,
    `  hash: ${JSON.stringify(validator.hash)},`,
    `  compiledCode: ${JSON.stringify(validator.compiledCode)},`,
    `} as const;`,
  ].join("\n");
}

/**
 * Produces one self-contained TypeScript module for the whole blueprint:
 * a named interface/union per Aiken `pub type`, and one typed
 * Datum/Redeemer alias plus a metadata constant per validator. This is
 * mechanical generation from CIP-57 (ADR-005) — never hand-maintained,
 * never a language-model call.
 */
export function generateSdkModule(blueprint: Blueprint): string {
  const namedTypes = generateNamedTypeDeclarations(blueprint);
  const validatorSections = blueprint.validators.map((validator) =>
    generateValidatorSection(blueprint, validator),
  );

  return [
    "// Generated by @forge/adapter-codegen-ts from a CIP-57 blueprint — do not edit by hand.",
    "",
    namedTypes,
    "",
    validatorSections.join("\n\n"),
    "",
  ].join("\n");
}
