import type { Blueprint, BlueprintSchema } from "@forge/domain";
import { resolveSchemaRef } from "@forge/domain";

function pascalCase(name: string): string {
  return name
    .split(/[_\s-]+/)
    .filter((part) => part.length > 0)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function camelCase(name: string): string {
  const pascal = pascalCase(name);
  return pascal.length > 0 ? pascal.charAt(0).toLowerCase() + pascal.slice(1) : pascal;
}

function refKey(ref: string): string {
  const prefix = "#/definitions/";
  const raw = ref.startsWith(prefix) ? ref.slice(prefix.length) : ref;
  return raw.replaceAll("~1", "/").replaceAll("~0", "~");
}

function definitionTypeName(definitionKey: string): string {
  const lastSegment = definitionKey.split("/").pop() ?? definitionKey;
  return pascalCase(lastSegment);
}

function primitiveTypeFor(dataType: string | undefined): string | undefined {
  switch (dataType) {
    case "integer":
      return "number";
    case "bytes":
      return "string";
    case "boolean":
      return "boolean";
    default:
      return undefined;
  }
}

/** A definition generated by an Aiken `pub type X { ... }` — one that needs a named TS declaration. */
function isConstructorType(schema: BlueprintSchema): boolean {
  return Boolean(schema.anyOf && schema.anyOf.length > 0);
}

/**
 * Resolves a schema to the TS type *expression* to use at a reference
 * site: either an inline primitive, or the name of a generated
 * interface/union declaration.
 */
export function typeExpressionFor(blueprint: Blueprint, schema: BlueprintSchema): string {
  if (schema.$ref) {
    const resolved = resolveSchemaRef(blueprint, schema.$ref);
    if (!resolved) {
      return "unknown";
    }
    if (isConstructorType(resolved)) {
      return definitionTypeName(refKey(schema.$ref));
    }
    return typeExpressionFor(blueprint, resolved);
  }

  const primitive = primitiveTypeFor(schema.dataType);
  if (primitive) {
    return primitive;
  }
  if (isConstructorType(schema)) {
    return "unknown";
  }
  return "unknown";
}

function fieldsToInterfaceBody(blueprint: Blueprint, fields: readonly BlueprintSchema[]): string {
  return fields
    .map((field) => {
      const fieldName = field.title ?? "value";
      return `  ${fieldName}: ${typeExpressionFor(blueprint, field)};`;
    })
    .join("\n");
}

/**
 * Emits one named TS declaration per Aiken `pub type` in the blueprint's
 * definitions: a plain `interface` for a single-constructor record, or a
 * tagged-union `type` alias for a multi-constructor enum.
 */
export function generateNamedTypeDeclarations(blueprint: Blueprint): string {
  const declarations: string[] = [];

  for (const [key, schema] of Object.entries(blueprint.definitions)) {
    if (!isConstructorType(schema)) {
      continue;
    }
    const typeName = definitionTypeName(key);
    const variants = schema.anyOf ?? [];

    if (variants.length === 1) {
      const [variant] = variants;
      const body = fieldsToInterfaceBody(blueprint, variant?.fields ?? []);
      declarations.push(
        body.length > 0
          ? `export interface ${typeName} {\n${body}\n}`
          : `export interface ${typeName} {}`,
      );
    } else {
      const members = variants.map((variant) => {
        const fields = variant.fields ?? [];
        const tag = `kind: "${variant.title ?? "Unknown"}"`;
        if (fields.length === 0) {
          return `  | { ${tag} }`;
        }
        return `  | { ${tag};\n${fieldsToInterfaceBody(blueprint, fields)}\n    }`;
      });
      declarations.push(`export type ${typeName} =\n${members.join("\n")};`);
    }
  }

  return declarations.join("\n\n");
}

export { camelCase, pascalCase };
