const STDLIB_VERSION = "v3.1.0";

export function buildAikenToml(packageName: string, compilerVersion: string): string {
  return `name = "forge/${packageName}"
version = "0.0.0"
compiler = "${compilerVersion}"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts generated by Forge"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "${STDLIB_VERSION}"
source = "github"
`;
}
