import { describe, expect, it } from "vitest";
import { BlueprintParseError, parseBlueprint } from "./blueprint-parser.js";

// Captured verbatim from a real `aiken build` run (Aiken v1.1.23) against
// the escrow-milestone validator, so the parser is verified against actual
// compiler output rather than an assumed shape.
const REAL_ESCROW_PLUTUS_JSON = JSON.stringify({
  preamble: {
    title: "forge/escrow-demo",
    description: "Aiken contracts generated by Forge",
    version: "0.0.0",
    plutusVersion: "v3",
    compiler: { name: "Aiken", version: "v1.1.23+8949565" },
    license: "Apache-2.0",
  },
  validators: [
    {
      title: "escrow_milestone.escrow_milestone.spend",
      datum: { title: "datum", schema: { $ref: "#/definitions/escrow_milestone~1EscrowDatum" } },
      redeemer: {
        title: "redeemer",
        schema: { $ref: "#/definitions/escrow_milestone~1EscrowRedeemer" },
      },
      compiledCode: "58db01010029...",
      hash: "4486d627a370e46712a13da34221f864c4bab449e7d13884926342b7",
    },
    {
      title: "escrow_milestone.escrow_milestone.else",
      redeemer: { schema: {} },
      compiledCode: "58db01010029...",
      hash: "4486d627a370e46712a13da34221f864c4bab449e7d13884926342b7",
    },
  ],
  definitions: {
    Int: { dataType: "integer" },
    "aiken/crypto/VerificationKeyHash": { title: "VerificationKeyHash", dataType: "bytes" },
    "escrow_milestone/EscrowDatum": {
      title: "EscrowDatum",
      anyOf: [
        {
          title: "EscrowDatum",
          dataType: "constructor",
          index: 0,
          fields: [
            { title: "beneficiary", $ref: "#/definitions/aiken~1crypto~1VerificationKeyHash" },
            { title: "milestones_completed", $ref: "#/definitions/Int" },
          ],
        },
      ],
    },
    "escrow_milestone/EscrowRedeemer": {
      title: "EscrowRedeemer",
      anyOf: [
        { title: "CompleteMilestone", dataType: "constructor", index: 0, fields: [] },
        { title: "Cancel", dataType: "constructor", index: 1, fields: [] },
      ],
    },
  },
});

describe("parseBlueprint", () => {
  it("parses a real Aiken blueprint into the domain Blueprint shape", () => {
    const blueprint = parseBlueprint(REAL_ESCROW_PLUTUS_JSON);

    expect(blueprint.preamble.plutusVersion).toBe("v3");
    expect(blueprint.validators).toHaveLength(1);
    expect(blueprint.validators[0]?.title).toBe("escrow_milestone.escrow_milestone.spend");
  });

  it("filters out the compiler-generated '.else' fallback purpose", () => {
    const blueprint = parseBlueprint(REAL_ESCROW_PLUTUS_JSON);

    expect(blueprint.validators.some((v) => v.title.endsWith(".else"))).toBe(false);
  });

  it("preserves $ref-based datum and redeemer schemas", () => {
    const blueprint = parseBlueprint(REAL_ESCROW_PLUTUS_JSON);
    const validator = blueprint.validators[0];

    expect(validator?.datum?.schema.$ref).toBe("#/definitions/escrow_milestone~1EscrowDatum");
    expect(validator?.redeemer.schema.$ref).toBe("#/definitions/escrow_milestone~1EscrowRedeemer");
  });

  it("parses nested constructor/anyOf/fields definitions", () => {
    const blueprint = parseBlueprint(REAL_ESCROW_PLUTUS_JSON);
    const datumDef = blueprint.definitions["escrow_milestone/EscrowDatum"];

    expect(datumDef?.anyOf?.[0]?.fields).toHaveLength(2);
    expect(datumDef?.anyOf?.[0]?.fields?.[0]?.title).toBe("beneficiary");
  });

  it("throws BlueprintParseError for invalid JSON", () => {
    expect(() => parseBlueprint("{not json")).toThrow(BlueprintParseError);
  });

  it("throws BlueprintParseError when the preamble is missing", () => {
    expect(() => parseBlueprint(JSON.stringify({ validators: [] }))).toThrow(BlueprintParseError);
  });

  it("throws BlueprintParseError when a validator is missing its redeemer", () => {
    const malformed = JSON.stringify({
      preamble: { title: "x", version: "0.0.0", plutusVersion: "v3" },
      validators: [{ title: "x.spend", compiledCode: "abc", hash: "abc" }],
    });

    expect(() => parseBlueprint(malformed)).toThrow(/missing a redeemer/);
  });
});
