// Verifies the admin wallet (generated by generate-admin-wallet.ts) is
// actually funded on preprod before we attempt any real deploy transaction.
// Run with: npx tsx --env-file=.env scripts/check-admin-balance.ts
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
import { MeshWallet } from "@meshsdk/core";
import { getPreprodProvider } from "../src/preprod-provider";

const __dirname = resolve(fileURLToPath(import.meta.url), "..");
const WALLET_PATH = resolve(__dirname, "../.secrets/admin-wallet.json");

async function main() {
  const saved = JSON.parse(readFileSync(WALLET_PATH, "utf-8")) as {
    mnemonic: string[];
    address: string;
  };

  const provider = getPreprodProvider();
  const wallet = new MeshWallet({
    networkId: 0,
    fetcher: provider,
    submitter: provider,
    key: { type: "mnemonic", words: saved.mnemonic },
  });
  await wallet.init();

  const balance = await wallet.getBalance();
  const lovelace = balance.find((a) => a.unit === "lovelace");
  const ada = lovelace ? Number(lovelace.quantity) / 1_000_000 : 0;

  console.log(`Address: ${saved.address}`);
  console.log(`Balance: ${ada} tADA`);
  if (ada === 0) {
    console.log("Not funded yet - use the faucet at https://docs.cardano.org/cardano-testnets/tools/faucet");
  } else {
    console.log("Funded and ready.");
  }
}

main().catch((error) => {
  console.error("Balance check failed:", error instanceof Error ? error.message : error);
  process.exit(1);
});
