// Task 5.1: computes the real preprod script addresses/hashes (using the
// admin wallet generated by generate-admin-wallet.ts) and posts the first
// genuine oracle price transaction. Records the results to
// deployments/preprod.json - that file holds only PUBLIC values (addresses,
// hashes, a tx hash), safe to commit, unlike .secrets/admin-wallet.json.
//
// Run with: npx tsx --env-file=.env scripts/deploy-preprod.ts
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
import { MeshWallet, resolvePlutusScriptAddress } from "@meshsdk/core";
import { loadValidators, scriptHash } from "../src/blueprint";
import { getPreprodProvider } from "../src/preprod-provider";
import { postPrice } from "../src/oracle-poster";
import { CONFIG } from "../src/config";

const __dirname = resolve(fileURLToPath(import.meta.url), "..");
const WALLET_PATH = resolve(__dirname, "../.secrets/admin-wallet.json");
const OUT_PATH = resolve(__dirname, "../deployments/preprod.json");

// ~1 week, in MILLISECONDS (the oracle deadline is POSIX-ms; see
// oracle-poster.ts). Long enough that the deploy doesn't need an active
// price-refreshing keeper running yet. A real keeper re-posting periodically
// is future work, noted in the demo's honest limitations.
const ORACLE_VALIDITY_WINDOW_MS = 7 * 24 * 60 * 60 * 1000;

async function main() {
  const saved = JSON.parse(readFileSync(WALLET_PATH, "utf-8")) as {
    mnemonic: string[];
    address: string;
    adminVkh: string;
  };

  const provider = getPreprodProvider();
  const wallet = new MeshWallet({
    networkId: 0,
    fetcher: provider,
    submitter: provider,
    key: { type: "mnemonic", words: saved.mnemonic },
  });
  await wallet.init();

  // Same key serves admin (reserve mint gate) and oracle (price-poster)
  // roles for this hackathon prototype - one fewer key to manage.
  const adminVkh = saved.adminVkh;
  const oracleVkh = saved.adminVkh;

  const validators = loadValidators();

  const reserveScript = validators.reserve(adminVkh);
  const tusdmPolicy = scriptHash(reserveScript);

  const oracleScript = validators.oracle(oracleVkh);
  const oracleHash = scriptHash(oracleScript);
  const oracleAddress = resolvePlutusScriptAddress(oracleScript, CONFIG.networkId);

  const reputationScript = validators.reputation();
  const reputationHash = scriptHash(reputationScript);

  console.log("Computed addresses:");
  console.log(`  reserve (tusdm_policy): ${tusdmPolicy}`);
  console.log(`  oracle hash:            ${oracleHash}`);
  console.log(`  oracle address:         ${oracleAddress}`);
  console.log(`  reputation hash:        ${reputationHash}`);

  console.log("\nPosting the first oracle price...");
  const { txHash } = await postPrice(
    { oracleAddress, validityWindowMs: ORACLE_VALIDITY_WINDOW_MS },
    {
      wallet,
      fetcher: provider,
      submitter: provider,
    },
  );

  console.log(`Oracle price posted: https://preprod.cardanoscan.io/transaction/${txHash}`);

  writeFileSync(
    OUT_PATH,
    JSON.stringify(
      {
        network: "preprod",
        adminVkh,
        oracleVkh,
        tusdmPolicy,
        tusdmAssetNameHex: CONFIG.tUSDM.assetNameHex,
        oracleHash,
        oracleAddress,
        reputationHash,
        firstOraclePriceTxHash: txHash,
        deployedAt: new Date().toISOString(),
      },
      null,
      2,
    ),
  );
  console.log(`\nRecorded to ${OUT_PATH}`);
}

main().catch((error) => {
  console.error("Deploy failed:", error instanceof Error ? error.message : error);
  process.exit(1);
});
