import type { Blueprint, DocumentationArtifact, Project, ReviewReport } from "@forge/domain";
import type { ILanguageModelPort } from "../ports/language-model.port.js";

export interface GenerateDocsInput {
  readonly project: Project;
  readonly blueprint: Blueprint;
  readonly review: ReviewReport;
}

export class GenerateDocsUseCase {
  constructor(private readonly languageModel: ILanguageModelPort | undefined) {}

  async execute(input: GenerateDocsInput): Promise<DocumentationArtifact> {
    const { project, blueprint, review } = input;
    const validatorList = blueprint.validators
      .map((validator) => `- \`${validator.title}\``)
      .join("\n");
    const header = `# ${project.name}\n\nGenerated by Forge.\n\n## Validators\n\n${validatorList}\n`;

    const rationales = review.observations.flatMap((observation) =>
      observation.relatedRationale ? [observation.relatedRationale] : [],
    );

    let notes: string;
    if (this.languageModel && rationales.length > 0) {
      notes = await this.languageModel.narrate({
        subject: `usage guide for ${project.name}`,
        facts: rationales,
      });
    } else {
      notes = review.observations.map((observation) => observation.summary).join("\n\n");
    }

    return {
      fileName: "GENERATED_README.md",
      content: `${header}\n## Review Notes\n\n${notes}\n`,
    };
  }
}
