import { z } from "zod";
import type { Brand } from "../shared/brand.js";

/**
 * Identifies a workflow/agent definition. Unlike ExecutionId, a
 * WorkflowId is never generated by Sentinel — it is a stable,
 * developer-assigned slug (e.g. "invoice-approval-agent") supplied at
 * SDK instrumentation time, and many Executions across time and across
 * versions share one WorkflowId. See ADR-0005.
 */
export type WorkflowId = Brand<string, "WorkflowId">;

const WORKFLOW_ID_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;

const workflowIdSchema = z
  .string()
  .min(1)
  .max(128)
  .regex(WORKFLOW_ID_PATTERN, "WorkflowId must be a lowercase slug (letters, digits, hyphens)");

export function parseWorkflowId(value: string): WorkflowId {
  return workflowIdSchema.parse(value) as WorkflowId;
}

export function isWorkflowId(value: string): value is WorkflowId {
  return workflowIdSchema.safeParse(value).success;
}
